version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: chat_app_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  cache:
    image: redis:latest
    container_name: chat_app_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  db_data:
  redis_data: